// <auto-generated />
using HomieManagement.Model.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HomieManagement.Migrations
{
    [DbContext(typeof(HomieManagementContext))]
    [Migration("20171103060118_v1")]
    partial class v1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HomieManagement.Model.DataBase.Firmware", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Binary");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<bool>("Disabled");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.Property<string>("Version");

                    b.HasKey("ID");

                    b.ToTable("Firmware");
                });
#pragma warning restore 612, 618
        }
    }
}
